### PR TITLE
Fix Panel Launcher

### PR DESCRIPTION
**Pull request by MarcSkovMadsen**
I believe `{--}panel` should be changed to `'{--}server=panel`. I've not been able to test it though.

### CODE REVIEW

**Comment by danlester** [comment]
Yes, I think you're right - maybe we changed it during development of bokeh-root-cmd.

**Comment by danlester** [comment]
Actually, the latest version of cdsdashboards code already contains this update -i.e. it uses --server=panel.

So I'll close without merging because I think we already have your change!

**Comment by danlester** [comment]
https://github.com/ideonate/cdsdashboards/blob/87c65eb4e54ea9772578ef2bbc396e95f4b43937/cdsdashboards/hubextension/spawners/variablemixin.py#L82

**Comment by MarcSkovMadsen** [comment]
Thanks. By the way I've gotten it working on our Jupyter hub and it works great.

**Pull request closed without merging**
